In [ ]:
!pip install streamlit

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix

In [21]:
data=pd.read_csv('Heart_Disease_Dataset.csv')

In [23]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,Yes,14.96,Yes,Yes,No,7,6,Yes,Female,25-29,White,Yes,Yes,Fair,17.1,Yes,Yes,Yes
1,Yes,36.93,Yes,Yes,No,3,10,No,Female,30-34,Hispanic,"No, borderline diabetes",Yes,Poor,2.7,Yes,No,No
2,No,18.70,Yes,No,Yes,26,15,No,Male,70-74,Hispanic,No,No,Poor,15.6,Yes,Yes,Yes
3,Yes,31.43,Yes,Yes,Yes,24,20,No,Female,40-44,American Indian/Alaskan Native,"No, borderline diabetes",No,Fair,1.4,No,No,Yes
4,Yes,75.64,No,No,Yes,2,29,No,Male,35-39,White,No,Yes,Excellent,8.8,Yes,Yes,Yes

In [40]:
data.size

1803618

In [44]:
data.tail()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
100196,No,48.02,No,No,Yes,13,17,No,Female,45-49,White,"No, borderline diabetes",No,Fair,6.4,Yes,No,No
100197,Yes,82.88,No,No,No,29,23,No,Male,75-79,Other,"No, borderline diabetes",Yes,Very good,18.9,Yes,Yes,No
100198,No,39.46,No,Yes,Yes,23,6,Yes,Male,80 or older,Hispanic,Yes,No,Excellent,18.5,Yes,No,Yes
100199,No,46.25,Yes,Yes,Yes,9,14,No,Male,25-29,American Indian/Alaskan Native,No,No,Very good,22.7,Yes,Yes,No
100200,No,39.26,Yes,No,No,10,5,Yes,Female,25-29,Other,"No, borderline diabetes",Yes,Fair,4.1,No,No,Yes

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100201 entries, 0 to 100200
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      100201 non-null  object
 1   BMI               100201 non-null  float64
 2   Smoking           100201 non-null  object
 3   AlcoholDrinking   100201 non-null  object
 4   Stroke            100201 non-null  object
 5   PhysicalHealth    100201 non-null  int64
 6   MentalHealth      100201 non-null  int64
 7   DiffWalking       100201 non-null  object
 8   Sex               100201 non-null  object
 9   AgeCategory       100201 non-null  object
 10  Race              100201 non-null  object
 11  Diabetic          100201 non-null  object
 12  PhysicalActivity  100201 non-null  object
 13  GenHealth         100201 non-null  object
 14  SleepTime         100201 non-null  float64
 15  Asthma            100201 non-null  object
 16  KidneyDisease     100201 non-null  object
 17  SkinCancer        100201 non-null  object
dtypes: float64(2), int64(2), object(14)
memory usage: 13.8+ MB

In [52]:
data.shape

(100201, 18)

### statastical analysis

In [59]:
data.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  100201.000000   100201.000000  100201.000000  100201.000000
mean       53.373302       14.503937      14.498239      12.490389
std        23.878712        8.640423       8.658639       6.632122
min        12.020000        0.000000       0.000000       1.000000
25%        32.760000        7.000000       7.000000       6.700000
50%        53.380000       14.000000      15.000000      12.500000
75%        73.950000       22.000000      22.000000      18.200000
max        94.850000       29.000000      29.000000      24.000000

In [63]:
data.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [85]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
100196    False
100197    False
100198    False
100199    False
100200    False
Length: 100201, dtype: bool

In [83]:
len(data[data.duplicated()])

0

In [87]:
data.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

In [95]:
for column in data.columns:
    print(data[column].value_counts())

HeartDisease
Yes    50134
No     50067
Name: count, dtype: int64
BMI
56.38    26
91.47    26
27.95    26
88.49    26
66.39    25
         ..
23.75     3
29.15     3
65.14     3
34.33     2
91.36     2
Name: count, Length: 8284, dtype: int64
Smoking
Yes    50445
No     49756
Name: count, dtype: int64
AlcoholDrinking
Yes    50435
No     49766
Name: count, dtype: int64
Stroke
Yes    50265
No     49936
Name: count, dtype: int64
PhysicalHealth
8     3430
20    3401
9     3395
16    3392
19    3386
13    3385
12    3377
26    3369
29    3363
15    3355
23    3354
22    3347
28    3345
14    3343
2     3341
1     3337
10    3334
11    3332
6     3329
0     3328
17    3327
7     3323
24    3316
5     3305
18    3301
3     3287
21    3285
27    3277
25    3270
4     3267
Name: count, dtype: int64
MentalHealth
27    3442
16    3442
13    3419
5     3403
26    3397
21    3394
22    3390
7     3382
2     3377
8     3376
1     3374
18    3367
14    3362
28    3361
6     3360
3     3357
20    3342
9     3336
23    3333
17    3317
0     3299
19    3284
25    3280
10    3279
29    3274
11    3269
4     3257
15    3252
12    3247
24    3229
Name: count, dtype: int64
DiffWalking
Yes    50153
No     50048
Name: count, dtype: int64
Sex
Female    50243
Male      49958
Name: count, dtype: int64
AgeCategory
80 or older    7851
18-24          7850
55-59          7801
40-44          7789
25-29          7710
75-79          7697
70-74          7694
45-49          7680
60-64          7673
35-39          7641
50-54          7634
65-69          7591
30-34          7590
Name: count, dtype: int64
Race
Hispanic                          16898
Asian                             16834
White                             16708
American Indian/Alaskan Native    16650
Black                             16582
Other                             16529
Name: count, dtype: int64
Diabetic
Yes (during pregnancy)     25171
No, borderline diabetes    25077
Yes                        25001
No                         24952
Name: count, dtype: int64
PhysicalActivity
No     50397
Yes    49804
Name: count, dtype: int64
GenHealth
Good         20342
Poor         20180
Fair         19986
Excellent    19939
Very good    19754
Name: count, dtype: int64
SleepTime
18.9    499
16.4    492
2.3     487
21.3    483
10.3    480
       ...
23.2    395
1.3     394
18.6    388
24.0    234
1.0     196
Name: count, Length: 231, dtype: int64
Asthma
Yes    50118
No     50083
Name: count, dtype: int64
KidneyDisease
Yes    50264
No     49937
Name: count, dtype: int64
SkinCancer
No     50426
Yes    49775
Name: count, dtype: int64